# Generated by Django 5.2.1 on 2025-05-18 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("image", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("replicas", models.IntegerField(default=1)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["label", "id"], name="deployment__label_c38f2a_idx"
                    )
                ],
            },
        ),
    ]
